# Generated by Django 5.0 on 2024-01-05 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_of_order",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(default=None, max_length=400, unique=True),
        ),
    ]
