# Generated by Django 5.0 on 2024-01-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseApp", "0003_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True, default=None, max_length=400, null=True, unique=True
            ),
        ),
    ]
