# Generated by Django 5.0 on 2024-01-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseApp", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
