# Generated by Django 5.0 on 2024-01-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseApp", "0005_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_item",
            new_name="order",
        ),
    ]
