# Generated by Django 5.0 on 2024-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseApp", "0006_rename_order_item_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_price",
            field=models.IntegerField(),
        ),
    ]
