# Generated by Django 5.0 on 2024-02-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_order_user'),
        ('baseApp', '0008_alter_orderitem_quantity'),
    ]

    operations = [
    ]
